#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see http://aka.ms/containercompat 

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-nanoserver-1809 AS base
WORKDIR /publish
EXPOSE 80

WORKDIR /app
COPY ./publish /publish .
ENTRYPOINT ["dotnet", "TestApiProject.dll"]